### ISSUE TITLE
ConnectionFactoryTestCase fails

### ISSUE THREAD

**Issue by tsujiguchitky** [openam-jp/opendj-sdk#2]
## Description

After updating to OpenJDK 8u201, the following test fails in opendj-grizzly.

* ConnectionFactoryTestCase.testBlockingPromiseNoHandler (Run6 & Run7)
* ConnectionFactoryTestCase.testNonBlockingPromiseWithHandler (Run6 & Run7)
* ConnectionFactoryTestCase.testSynchronousConnection (Run6 & Run7)

## Steps to reproduce

```
$ mvn test -f opendj-grizzly
```

## Enviroment

* CentOS 7.6
* java-1.8.0-openjdk-1.8.0.201.b09-2.el7_6.x86_64

## Build Log

```
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running TestSuite
Configuring TestNG with: TestNG652Configurator

Test environment:

  Java version: 1.8.0_201
  Java vendor:  Oracle Corporation
  JVM name:     OpenJDK 64-Bit Server VM
  JVM version:  25.201-b09
  JVM vendor:   Oracle Corporation
  JVM info:     mixed mode
  Java home:    /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.201.b09-2.el7_6.x86_64/jre
  OS:           Linux 3.10.0-862.3.3.el7.x86_64 amd64
  Processors:   8
  Max memory:   7453278208
  Total memory: 502792192

How to read the progressive status info:

  Test duration status: {Total min:sec.  Since last status sec.}
  Test count status:  {# test classes  # test methods  # test method invocations  # test failures}.
  TestClass (the class that just completed)

{ 0:00 (  1s)}  {  0c    0m     0i 0f}  : starting
{ 0:01 (  1s)}  {  1c    8m     8i 0f}  : GrizzlyLDAPConnectionFactoryTestCase 
{ 0:01 (  0s)}  {  2c   16m    16i 0f}  : GrizzlyLDAPListenerTestCase 
{ 0:01 (  0s)}  {  3c   61m   686i 0f}  : ASN1BufferReaderTestCase 
{ 0:02 (  0s)}  {  4c   78m   928i 0f}  : ASN1BufferWriterTestCase 
{ 0:02 (  0s)}  {  5c   80m   930i 0f}  : GrizzlyLDAPConnectionTestCase 
{ 0:02 (  0s)}  {  6c   81m   953i 0f}  : GrizzlyLDAPReaderWriterTestCase 
{ 0:02 (  0s)}  {  7c   86m   958i 0f}  : GrizzlyUtilsTestCase 
Mar 28, 2019 7:45:19 AM org.glassfish.grizzly.filterchain.DefaultFilterChain execute
WARNING: GRIZZLY0013: Exception during FilterChain execution
java.lang.IllegalArgumentException: CipherSuites may not be null
	at sun.security.ssl.CipherSuiteList.<init>(CipherSuiteList.java:74)
	at sun.security.ssl.SSLEngineImpl.setEnabledCipherSuites(SSLEngineImpl.java:2027)
	at org.glassfish.grizzly.ssl.SSLEngineConfigurator.configure(SSLEngineConfigurator.java:233)
	at org.glassfish.grizzly.ssl.SSLEngineConfigurator.createSSLEngine(SSLEngineConfigurator.java:215)
	at org.glassfish.grizzly.ssl.SSLFilter.createClientSSLEngine(SSLFilter.java:345)
	at org.glassfish.grizzly.ssl.SSLFilter.handshake(SSLFilter.java:240)
	at org.glassfish.grizzly.ssl.SSLFilter.handshake(SSLFilter.java:224)
	at org.glassfish.grizzly.ssl.SSLFilter.handshake(SSLFilter.java:207)
	at org.forgerock.opendj.grizzly.GrizzlyLDAPConnection.startTLS(GrizzlyLDAPConnection.java:832)
	at org.forgerock.opendj.grizzly.LDAPClientFilter$ClientResponseHandler.handleExtendedResult0(LDAPClientFilter.java:377)
	at org.forgerock.opendj.grizzly.LDAPClientFilter$ClientResponseHandler.extendedResult(LDAPClientFilter.java:257)
	at org.forgerock.opendj.io.LDAPReader.readExtendedResult(LDAPReader.java:387)
	at org.forgerock.opendj.io.LDAPReader.readProtocolOp(LDAPReader.java:595)
	at org.forgerock.opendj.io.LDAPReader.readMessage(LDAPReader.java:132)
	at org.forgerock.opendj.grizzly.LDAPBaseFilter.handleRead(LDAPBaseFilter.java:82)
	at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:119)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:283)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:200)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:132)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:111)
	at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:77)
	at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:536)
	at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:112)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:117)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:56)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:137)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:591)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:571)
	at java.lang.Thread.run(Thread.java:748)




                 T E S T   F A I L U R E ! ! !

Failed Test:  org.forgerock.opendj.grizzly.ConnectionFactoryTestCase#testBlockingPromiseNoHandler
Failure Cause:  java.util.concurrent.ExecutionException: org.forgerock.opendj.ldap.ConnectionException: Connect Error: The connection attempt to server localhost/127.0.0.1:43178 has failed because the connection timeout period of 10000 ms was exceeded
    org.forgerock.util.promise.PromiseImpl.get0(PromiseImpl.java:577)
    org.forgerock.util.promise.PromiseImpl.get(PromiseImpl.java:132)
    org.forgerock.opendj.grizzly.ConnectionFactoryTestCase.testBlockingPromiseNoHandler(ConnectionFactoryTestCase.java:271)
parameter[0]: LDAPConnectionFactory(provider=`Grizzly, host='localhost', port=43178, options=org.forgerock.util.Options@2dcd168a)


-------------------------------------------------------------------------------

...(Omitted)...

Results :

Failed tests: 
org.forgerock.opendj.grizzly.ConnectionFactoryTestCase.testBlockingPromiseNoHandler(org.forgerock.opendj.grizzly.ConnectionFactoryTestCase)
  Run 1: PASS
  Run 2: PASS
  Run 3: PASS
  Run 4: PASS
  Run 5: PASS
  Run 6: ConnectionFactoryTestCase.testBlockingPromiseNoHandler:271 ? Execution org.for...
  Run 7: ConnectionFactoryTestCase.testBlockingPromiseNoHandler:271 ? Execution org.for...
  Run 8: PASS

...(Omitted)...

Tests run: 974, Failures: 3, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
```

**Comment by tsujiguchitky** [comment]
Failed tests use startTLS for LDAP connection. And they use anonymous cipher suites. Therefore, the following fix seems to be affecting.

[[JDK-8211883] Disable anon and NULL cipher suites](https://bugs.openjdk.java.net/browse/JDK-8211883)

https://hg.openjdk.java.net/jdk8u/jdk8u/jdk/rev/e146b597c4da

**Comment by tsujiguchitky** [comment]
## Workaround

Modify `jdk.tls.disabledAlgorithms` security properties.

```
diff --git a/java.security b/java.security
index 9de2c1d..5705f29 100644
--- a/java.security
+++ b/java.security
@@ -624,7 +624,7 @@ jdk.jar.disabledAlgorithms=MD2, MD5, RSA keySize < 1024, DSA keySize < 1024
 # Example:
 #   jdk.tls.disabledAlgorithms=MD5, SSLv3, DSA, RSA keySize < 2048
 jdk.tls.disabledAlgorithms=SSLv3, RC4, DES, MD5withRSA, DH keySize < 1024, \
-    EC keySize < 224, 3DES_EDE_CBC, anon, NULL
+    EC keySize < 224, 3DES_EDE_CBC, NULL
 
 # Legacy algorithms for Secure Socket Layer/Transport Layer Security (SSL/TLS)
 # processing in JSSE implementation.
```
